version: '3.6'
services:
  wordpress:
    build:
      context: .
    volumes:
      - ./:/var/www/html/wp-content/plugins/ups-blocks:cached
      - ./logs:/var/www/html/logs
    depends_on:
      - db
    ports:
      - '8888:80'
    environment:
      # WordPress install configuration
      WORDPRESS_TITLE: 'Ups Blocks WordPress Plugin'
      WORDPRESS_URL: http://localhost:8888
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_EMAIL: admin@example.com
      WORDPRESS_ADMIN_PASSWORD: password

      # WordPress database configuration
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

      # Runtime configuration for richarvey/nginx-php-fpm
      # See https://github.com/richarvey/nginx-php-fpm
      RUN_SCRIPTS: 1

      # Comment out this next line to avoid permissions issues when not mounting the
      # theme codebase into the container via `volumes` in `docker-composer.yml`.
      # We're skipping it by default as it's not strictly required when using `volumes`
      # and it adds significantly to boot time with larger codebases.
      SKIP_CHOWN: 1

      # Set the time zone
      TZ: America/New_York
  db:
    image: mysql:5.7
    volumes:
      # Export an initial DB seed using `wp db export` and load it automatically on first install
      # See https://hub.docker.com/_/mysql
      # - ./docker/conf/mysql/init.sql.gz:/docker-entrypoint-initdb.d/init.sql.gz
      - db_data:/var/lib/mysql
    environment:
      # See https://hub.docker.com/_/mysql/
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
volumes:
  db_data:
