name: Build Assets for Release
on:
  release:
    types: [created]
jobs:
  build:
    name: Upload release asset
    runs-on: ubuntu-latest
    steps:
      - name: Create temp directory
        run: mkdir _tmp
