name: Build and commit assets

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: build
          message: 'Build production assets (from GitHub Actions)'
